language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eugene2238/dashboard_angular-unittests -f ./docker/chromium/Dockerfile .
  - docker build -t eugene2238/dashboard_angular-e2e-tests -f ./docker/angular-e2e/Dockerfile .

script:
  - docker run -e CI=true eugene2238/dashboard_angular-unittests npm run testChromiumNoSandbox
  - docker run -e CI=true eugene2238/dashboard_angular-e2e-tests npm run e2e

after_success:
  - docker build -t eugene2238/dashboard-frontend -f ./docker/node/Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push eugene2238/dashboard-frontend
